/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2014-12-11 00:30:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import apimanager.*;
import java.util.*;
import beans.*;
import dao.*;

public final class AdminProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("    ");

    if ((session.getAttribute("userid") == null) || (session.getAttribute("userid") == "") || (session.getAttribute("role") == "User")) {

      out.write("\r\n");
      out.write("You are not logged in<br/>\r\n");
      out.write("<a href=\"index.jsp\">Please Login</a>\r\n");
} else {
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/bootstrap-theme.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/bootstrap-theme.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".table td {\r\n");
      out.write("   text-align: center;   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table th {\r\n");
      out.write("   text-align: center;   \r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");


String username = (String)session.getAttribute("userid");

UserManager userManager = new UserManager();

User user = userManager.findByUsername(username);

BookingManager bookingManager = new BookingManager();

List<Booking> bookings = bookingManager.findAllBookingsForUser(username);

HotelManager hotelManager = new HotelManager();

List<String> locations = new LinkedList<String>();


locations = bookingManager.findallhotellocationforUser(username);

ReviewManager rvm = new ReviewManager();

List<Review> reviews = new ArrayList<Review>();

reviews = (List<Review>)rvm.findAllReviewsForUser(username);

FollowManager followManager = new FollowManager();

List<Follow> followers = followManager.findAllFollowersForUser(username);

List<Follow> followed = followManager.findFollowingOfUser(username);





      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function submitOtherUser(otheruser){\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#otheruser\").val(otheruser);\r\n");
      out.write("\t\r\n");
      out.write("\tvar o = $(\"#otheruser\").val();\r\n");
      out.write("\t$(\"#userInfo\").submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function gotohotel(id)\r\n");
      out.write("{\r\n");
      out.write("    var url =\"http://localhost:8080/HotelReservationSystem/HotelInfo.jsp?hotelID=\";\r\n");
      out.write("    \r\n");
      out.write("    alert(url);\r\n");
      out.write("    url = url\r\n");
      out.write("    //window.location.href = url;\r\n");
      out.write("}\r\n");
      out.write("function ajaxBookingdetails(){\r\n");
      out.write("\t\r\n");
      out.write("\tvar location = $(\"#location\").val();\r\n");
      out.write("\tvar username = \"");
      out.print( username);
      out.write("\";\r\n");
      out.write("\t\r\n");
      out.write("\tif (location != -1)\r\n");
      out.write("\t{\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("            url: \"MyProfileAjax.jsp\",\r\n");
      out.write("            type: \"POST\",\r\n");
      out.write("            data : {\r\n");
      out.write("            \tlocation : location,\r\n");
      out.write("            \tusername : username\r\n");
      out.write("            \t\r\n");
      out.write("            },\r\n");
      out.write("            success : function(response){\r\n");
      out.write("                 var content = $(response).filter('div#booking-details').html();\r\n");
      out.write("             //   console.log(content);\r\n");
      out.write("                             $(\"#booking-details\").html(content);\r\n");
      out.write("                          //   findDataAndNotifyResponse(response);\r\n");
      out.write("              //  $('input#txtEduInst').attr('data-source',instload);\r\n");
      out.write("               //  $('.typeahead').typeahead();\r\n");
      out.write("               // $('input#txtEduInst').typeahead();\r\n");
      out.write("                 }\r\n");
      out.write("        });\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-default navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("          <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">\r\n");
      out.write("            <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <a class=\"navbar-brand\" href=\"AdminHome.jsp\">FindMyHotels.com</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("          <ul class=\"nav navbar-nav\">\r\n");
      out.write("            <li class=\"active\"><a href=\"#\">Manage Booking</a></li>\r\n");
      out.write("            <li><a href=\"AdminHome.jsp\">Find Hotels</a></li>\r\n");
      out.write("            <li><a href=\"AdminManageBooking.jsp\">Manage booking</a></li>\r\n");
      out.write("            <li><a href=\"AdminManageReview.jsp\">Manage Review</a></li>\r\n");
      out.write("            \r\n");
      out.write("          </ul>\r\n");
      out.write("          <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("          <li><a href=\"AdminUserCreate.jsp\">Create User</a></li>\r\n");
      out.write("            <li><a href=\"AdminProfile.jsp\">My Profile</a></li>\r\n");
      out.write("            <li><a href=\"logout.jsp\">Logout</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div><!--/.nav-collapse -->\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("<div class=\"container\" style=\"padding-top: 70px\">\r\n");
      out.write("\t<div class=\"well well=lg\">\r\n");
      out.write("\t<div class=\"well well=sm\">\r\n");
      out.write("<center>\r\n");
      out.write("\r\n");
      out.write("            <table class=\"table\" width=\"30%\" cellpadding=\"5\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th colspan=\"2\">Profile Details</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>First Name</td>\r\n");
      out.write("                        <td>");
      out.print(user.getFirstname() );
      out.write("</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>Last Name</td>\r\n");
      out.write("                        <td>");
      out.print(user.getLastname());
      out.write("</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>DOB</td>\r\n");
      out.write("                        <td>");
      out.print(user.getDob());
      out.write("</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                        <form method=\"post\" action=\"EditProfile.jsp\">\r\n");
      out.write("                        <input type=\"hidden\" value=\"");
      out.print(username );
      out.write("\"/> \r\n");
      out.write("                        <input type=\"submit\" class=\"btn btn-primary\" value=\"Edit\"/>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td><form method=\"post\" action=\"ChangePassword.jsp\">\r\n");
      out.write("                        <input type=\"hidden\" value=\"");
      out.print(username );
      out.write("\"/> \r\n");
      out.write("                        <input type=\"submit\" class=\"btn btn-primary\" value=\"Change Password\"/>\r\n");
      out.write("                        </form></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    \r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("            </center>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("            <br>\r\n");
      out.write("                 </div>\r\n");
      out.write("          </div>\r\n");
      out.write("            \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");

    }

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
