/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2014-12-11 00:31:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import apimanager.*;
import java.util.*;
import beans.*;
import dao.*;

public final class HotelInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    if ((session.getAttribute("userid") == null) || (session.getAttribute("userid") == "")) {

      out.write("\r\n");
      out.write("You are not logged in<br/>\r\n");
      out.write("<a href=\"index.jsp\">Please Login</a>\r\n");
} else {
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");

	 String username = (String)session.getAttribute("userid");
	String hotelID = (String) request.getParameter("hotelID");
String arrivalDate = (String) request.getParameter("arrivalDate");
String departureDate = (String) request
.getParameter("departureDate");

RatingManager manager = new RatingManager();



Rating  getrating = manager.findAllRatingsForHotelandUser(username,hotelID);

Boolean r = false;

if ( getrating != null)
	r = true;

List<Rating> avgrat = manager.findAllRatingsForHotel(hotelID);
Integer averagerating = 0;

if(avgrat.size()>0){
	
	for(Rating ra : avgrat){
		
		averagerating += ra.getValue();
	}
	
	averagerating = averagerating/avgrat.size();
}

HotelManager hotelManager = new  HotelManager();

	WebServiceClient client = new WebServiceClient();
	HotelInfo hotel = client.getHotelInfomation(hotelID);
	hotel.setArrivalDate(arrivalDate);
	hotel.setDepartureDate(departureDate);
	

	System.out.println("In HotelInfo JSP");
	
	String appendImageURL = "http://images.travelnow.com/";
	
	int i = 0;
	
	 
	  String hotelIDajax = (String)request.getParameter("hotelIDajax");
	  
	  Likes l = new Likes();
	  
	  LikeManager likeManager = new LikeManager();
	  
	  l = likeManager.findLike(username, hotelID);
	  
	  Boolean b ;
	  
	  if(l == null)
	  {
		  b = true;
		  System.out.println("No like found");
	  }
	  else
		  b = false;
	  
	  RateValueManager rateValueManager = new RateValueManager();
	  
	  List<RateValue> values = rateValueManager.findAllRateValues();
	  
	  ReviewManager rvm = new ReviewManager();
	  
	  List<Review> reviews = new ArrayList<Review>();
	  
	  reviews = (List<Review>)rvm.findAllReviewsForHotel(hotelID);
	  
	  System.out.println(reviews.size());
	  
	  
	  
	 
	  

      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/bootstrap-theme.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/bootstrap-theme.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.js\"></script>\r\n");
if(getrating != null){ 
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$( document ).ready(function() {\r\n");
      out.write("    $(\"#ratingvalue\").val(\"");
      out.print(getrating.getValue());
      out.write("\");\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
 } 
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction submitOtherUser(otheruser){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#otheruser\").val(otheruser);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar o = $(\"#otheruser\").val();\r\n");
      out.write("\t\t$(\"#userInfo\").submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction ajaxaddRating(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar rating = $(\"#ratingvalue\").val();\r\n");
      out.write("\t\tvar hotelIDajax =$(\"#hotelIDajax\").val();\r\n");
      out.write("\t    var username = $(\"#username\").val();\r\n");
      out.write("\t\tif(rating != -1)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t $.ajax({\r\n");
      out.write("\t\t\t        url: \"RateIt.jsp\",\r\n");
      out.write("\t\t\t        type: \"POST\",\r\n");
      out.write("\t\t\t        data : {\r\n");
      out.write("\t\t\t            username : username,\r\n");
      out.write("\t\t\t            hotelIDajax : hotelIDajax,\r\n");
      out.write("\t\t\t            rating : rating\r\n");
      out.write("\t\t\t        },\r\n");
      out.write("\t\t\t        success : function(response){\r\n");
      out.write("\t\t\t             var content = $(response).filter('div#rating').html();\r\n");
      out.write("\t\t\t         \r\n");
      out.write("\t\t\t                         $(\"#rating\").html(content);\r\n");
      out.write("\t\t\t                         \r\n");
      out.write("\t\t\t             }\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("    function like()\r\n");
      out.write("    {  //alert(\"Hi\")\r\n");
      out.write("        var hotelIDajax =$(\"#hotelIDajax\").val();\r\n");
      out.write("     \tvar username = $(\"#username\").val();\r\n");
      out.write("       // alert(hotelIDajax);\r\n");
      out.write("      //  alert(username);\r\n");
      out.write("     \r\n");
      out.write("        $.ajax({\r\n");
      out.write("        url: \"Like.jsp\",\r\n");
      out.write("        type: \"POST\",\r\n");
      out.write("        data : {\r\n");
      out.write("            username : username,\r\n");
      out.write("            hotelIDajax : hotelIDajax\r\n");
      out.write("        },\r\n");
      out.write("        success : function(response){\r\n");
      out.write("             var content = $(response).filter('div#search-results3').html();\r\n");
      out.write("         \r\n");
      out.write("                         $(\"#search-results3\").html(content);\r\n");
      out.write("                         findDataAndNotifyResponse(response);\r\n");
      out.write("             }\r\n");
      out.write("    });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    function ajaxAddReview(){\r\n");
      out.write("    \t\r\n");
      out.write("        var hotelIDajax =$(\"#hotelIDajax\").val();\r\n");
      out.write("      \tvar username = $(\"#username\").val();\r\n");
      out.write("    \tvar title = $(\"#title\").val();\r\n");
      out.write("    \tvar review = $.trim($(\"textarea\").val());\r\n");
      out.write("    \tvar rating = $(\"#rating\").val();\r\n");
      out.write("    \t\r\n");
      out.write("    \t$.ajax({\r\n");
      out.write("            url: \"Review.jsp\",\r\n");
      out.write("            type: \"POST\",\r\n");
      out.write("            data : {\r\n");
      out.write("            \thotelIDajax : hotelIDajax,\r\n");
      out.write("            \tusername : username,\r\n");
      out.write("            \ttitle : title,\r\n");
      out.write("            \treview : review,\r\n");
      out.write("            \trating : rating\r\n");
      out.write("            },\r\n");
      out.write("            success : function(response){\r\n");
      out.write("                 var content = $(response).filter('div#all-reviews').html();\r\n");
      out.write("             \r\n");
      out.write("                             $(\"#all-reviews\").html(content);\r\n");
      out.write("                         \r\n");
      out.write("                 }\r\n");
      out.write("        });\r\n");
      out.write("    \t\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
 if (String.valueOf(session.getAttribute("role")).equals("Admin")) {
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-default navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("          <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">\r\n");
      out.write("            <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <a class=\"navbar-brand\" href=\"AdminHome.jsp\">FindMyHotels.com</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("          <ul class=\"nav navbar-nav\">\r\n");
      out.write("            <li class=\"active\"><a href=\"#\">");
      out.print(hotel.getName() );
      out.write("</a></li>\r\n");
      out.write("            <li><a href=\"AdminHome.jsp\">Find Hotels</a></li>\r\n");
      out.write("            <li><a href=\"AdminManageBooking.jsp\">Manage booking</a></li>\r\n");
      out.write("             <li><a href=\"AdminManageReview.jsp\">Manage Review</a></li>\r\n");
      out.write("            \r\n");
      out.write("          </ul>\r\n");
      out.write("          <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("          <li><a href=\"AdminUserCreate.jsp\">Create User</a></li>\r\n");
      out.write("            <li><a href=\"AdminProfile.jsp\">My Profile</a></li>\r\n");
      out.write("            <li><a href=\"logout.jsp\">Logout</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div><!--/.nav-collapse -->\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
 } else { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<nav class=\"navbar navbar-default navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("          <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">\r\n");
      out.write("            <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <a class=\"navbar-brand\" href=\"HomeSearch.jsp\">FindMyHotels.com</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("          <ul class=\"nav navbar-nav\">\r\n");
      out.write("            <li class=\"active\"><a href=\"#\">");
      out.print(hotel.getName() );
      out.write("</a></li>\r\n");
      out.write("            <li><a href=\"HomeSearch.jsp\">Find Hotels</a></li>\r\n");
      out.write("            <li><a href=\"#contact\">Contact</a></li>\r\n");
      out.write("            \r\n");
      out.write("          </ul>\r\n");
      out.write("          <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("             <li><a href=\"MyProfile.jsp\">My Profile</a></li>\r\n");
      out.write("            <li><a href=\"logout.jsp\">Logout</a></li>\r\n");
      out.write("            \r\n");
      out.write("          </ul>\r\n");
      out.write("        </div><!--/.nav-collapse -->\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("\t<div class=\"container\" style=\"padding-top: 70px\">\r\n");
      out.write("<div class=\"well well-lg\">\r\n");
      out.write("\t<center>\r\n");
      out.write("\t<div class=\"well well-sm\" style=\"width: 350px; height: 300px;\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div id=\"carousel-example-generic\" class=\"carousel slide\"\r\n");
      out.write("\t\t\tdata-ride=\"carousel\">\r\n");
      out.write("\t\t\t<!-- Indicators -->\r\n");
      out.write("\t\t\t<ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t\t");
for ( i = 0; i < 10;i++){ 
      out.write("\r\n");
      out.write("\t\t\t\t<li data-target=\"#carousel-example-generic\" data-slide-to=\"");
      out.print(i );
      out.write("\"\r\n");
      out.write("\t\t\t\t\tclass=\"active\"></li>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</ol>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Wrapper for slides -->\r\n");
      out.write("\t\t\t<div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("\t\t\t\t");
for ( i = 0; i < hotel.getImagesURL().size();i++) { 
      out.write("\r\n");
      out.write("\t\t\t\t");
if (i==1)
    	{
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"item active\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.print(hotel.getImagesURL().get(i) );
      out.write("\" alt=\"...\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"img-rounded\" style=\"width: 300px; height: 250px;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-caption\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
} else {
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.print(hotel.getImagesURL().get(i) );
      out.write("\" alt=\"...\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"img-rounded\" style=\"width: 300px; height: 250px;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-caption\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
} }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Controls -->\r\n");
      out.write("\t\t<a style=\"width: 1082px; height: 453px;\" class=\"carousel-control\"\r\n");
      out.write("\t\t\thref=\"#carousel-example-generic\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("\t\t\t<span class=\"glyphicon glyphicon-chevron-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t<span class=\"sr-only\">Previous</span>\r\n");
      out.write("\t\t</a> <a style=\"width: 1609px; height: 453px;\" class=\"carousel-control\"\r\n");
      out.write("\t\t\thref=\"#carousel-example-generic\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("\t\t\t<span class=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t<span class=\"sr-only\">Next</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</center>\r\n");
      out.write("\t<div class=\"jumbotron\">\r\n");
      out.write("\t\t<h1>");
      out.print(hotel.getName() );
      out.write("</h1>\r\n");
      out.write("\t\t<div id=\"change-rating\"><h3>\r\n");
      out.write("\t\t");
if (averagerating == 0) { 
      out.write("\r\n");
      out.write("\t\t<em>Average Rating : -/5 </em>\r\n");
      out.write("\t\t");
} else { 
      out.write("\r\n");
      out.write("\t\t<em>Average Rating : ");
      out.print(averagerating );
      out.write("/5 </em>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</h3></div>\r\n");
      out.write("\t\t");
      out.print(hotel.getPropertyDesc() );
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<form method=\"post\" action=\"BookingForm.jsp\">\r\n");
      out.write("\t\t\t<input name=\"hotelID\" value=\"");
      out.print(hotelID);
      out.write("\" type=\"hidden\" /> <input\r\n");
      out.write("\t\t\t\tname=\"arrivalDate\" type=\"hidden\" value=\"");
      out.print(hotel.getArrivalDate());
      out.write("\">\r\n");
      out.write("\t\t\t<input name=\"departureDate\" type=\"hidden\"\r\n");
      out.write("\t\t\t\tvalue=\"");
      out.print(hotel.getDepartureDate());
      out.write("\"> <input\r\n");
      out.write("\t\t\t\tclass=\"btn btn-primary form-control\"   name=\"submit\" value=\"Book\" type=\"submit\" />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t");
 if (String.valueOf(session.getAttribute("role")).equals("User")) {
      out.write("\r\n");
      out.write("\t\t<form method=\"post\" action=\"index.jsp\">\r\n");
      out.write("\t\t\t<input name=\"hotelID\" value=\"");
      out.print(hotelID);
      out.write("\" type=\"hidden\" /> \r\n");
      out.write("\t\t\t");
if (b == true) { 
      out.write("\r\n");
      out.write("\t\t\t<div id=\"search-results3\">\r\n");
      out.write("\t\t\t<input\r\n");
      out.write("\t\t\t\tclass=\"btn btn-success form-control\" name=\"submit\" value=\"Like\" type=\"button\" onclick=\"like();\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
} else { 
      out.write("\r\n");
      out.write("\t\t\t<div id=\"search-results3\">\r\n");
      out.write("<input class=\"btn btn-warning form-control\"  name=\"submit\" value=\"UnLike\" type=\"button\" onclick=\"like();\" />\r\n");
      out.write("</div>\r\n");
} 
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("<input name=\"hotelIDajax\" id=\"hotelIDajax\" value=\"");
      out.print(hotelID);
      out.write("\" type=\"hidden\" />\r\n");
      out.write("<input name=\"username\"  id=\"username\" value=\"");
      out.print((String)session.getAttribute("userid"));
      out.write("\" type=\"hidden\" />\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"rating\" class=\"span4\">\r\n");
      out.write("   \t\t<label>Rate It :</label>\r\n");
      out.write("      <select\r\n");
      out.write("      ");
if(r == true) { 
      out.write("\r\n");
      out.write("      disabled=\"disabled\"\r\n");
      out.write("      ");
} 
      out.write("\r\n");
      out.write("       onchange=\"ajaxaddRating();\" class=\"form-control\" id=\"ratingvalue\" name=\"rating\">\r\n");
      out.write("      <option value=\"-1\">Rate it.!!</option>\r\n");
      out.write("      ");
for(RateValue rv : values) { 
      out.write("\r\n");
      out.write("     \r\n");
      out.write("      <option value=\"");
      out.print(rv.getValue());
      out.write('"');
      out.write('>');
      out.print(rv.getValue() );
      out.write("</option>\r\n");
      out.write("     \r\n");
      out.write("      ");
} 
      out.write("\r\n");
      out.write("      </select>\r\n");
      out.write("   \r\n");
      out.write("  </div>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div id=\"all-reviews\" class=\"well well-sm\">\r\n");
      out.write("\t<h4>Reviews</h4>\r\n");
      out.write("\t");
if(reviews.size() == 0) { 
      out.write("\r\n");
      out.write("\t<p>No Reviews Found</p>\r\n");
      out.write("\t");
} 
      out.write('\r');
      out.write('\n');
      out.write('	');
for (int j =0;j<reviews.size();j++)  {
      out.write("\r\n");
      out.write("\t<div id=\"review_");
      out.print(reviews.get(j).getReviewId() );
      out.write("\" class=\"well well-sm\">\r\n");
      out.write("\t<h4><em>");
      out.print(reviews.get(j).getTitle() );
      out.write("</em></h4>\r\n");
      out.write("\t<p><em>");
      out.print(reviews.get(j).getReview() );
      out.write("</em></p>\r\n");
      out.write("\t");
if (!(String.valueOf(session.getAttribute("userid")).equals(reviews.get(j).getUserName()))) {
      out.write("\r\n");
      out.write("\t<p><a onclick=\"submitOtherUser('");
      out.print( reviews.get(j).getUserName());
      out.write("');\"><em>User : ");
      out.print( reviews.get(j).getUserName() );
      out.write("</em></a></p>\r\n");
      out.write("\t");
 } else { 
      out.write("\r\n");
      out.write("\t<p><em>User : ");
      out.print( reviews.get(j).getUserName() );
      out.write("</em></p>\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t<h4>Add Reviews</h4>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label for=\"exampleInputEmail1\">Title</label>\r\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"title\" placeholder=\"Title\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label for=\"exampleInputPassword1\">Review</label>\r\n");
      out.write("    <textarea  class=\"form-control\" id=\"review\">\r\n");
      out.write("    </textarea>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <button type=\"submit\" class=\"btn btn-success form-control\" onclick=\"ajaxAddReview();\">Submit</button>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<form action=\"UserProfile.jsp\" id=\"userInfo\" name=\"userInfo\" method=\"post\">\r\n");
      out.write("\t<input name=\"otheruser\" id=\"otheruser\" value=\"\" type=\"hidden\"/>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");

    }

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
