/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2014-12-12 00:09:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import apimanager.*;
import java.util.*;
import beans.*;
import dao.*;

public final class Review_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/bootstrap-theme.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/bootstrap-theme.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("</head>\r\n");

  String username = (String)request.getParameter("username");
  String hotelIDajax = (String)request.getParameter("hotelIDajax");
  String title = (String)request.getParameter("title");
  String review = (String)request.getParameter("review");
  String rating = (String)request.getParameter("rating");
  
  HotelManager hotelManager = new HotelManager();
  
  Hotel hotel = hotelManager.findHotel(hotelIDajax);
  
  if(hotel == null)
	{
	     WebServiceClient client = new WebServiceClient();
		HotelInfo hotelinfo  = new HotelInfo();
		hotelinfo = client.getHotelInfomation(hotelIDajax);
		
		Hotel newhotel = new Hotel();
		newhotel.setHotelId(hotelinfo.getHotelID());
		newhotel.setName(hotelinfo.getName());
		newhotel.setLocation(hotelinfo.getCity());
		
		newhotel = hotelManager.createHotel(newhotel);
		
	}
  ReviewManager rvm = new ReviewManager();
  
  Review r = new Review();
  
  r.setHotelId(hotelIDajax);
  r.setUserName(username);
  r.setTitle(title);
  r.setReview(review);
  
  rvm.createReview(r);
  
  
  
  
  RateValueManager rateValueManager = new RateValueManager();
  
  List<RateValue> values = rateValueManager.findAllRateValues();
  
  
  
  List<Review> reviews = new ArrayList<Review>();
  
  reviews = (List<Review>)rvm.findAllReviewsForHotel(hotelIDajax);
  
  
  
  
  
  
  


      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<br>\r\n");
      out.write("\t<div id=\"all-reviews\" class=\"well well-lg\">\r\n");
      out.write("\t<h4>Reviews</h4>\r\n");
      out.write("\t");
for (int j =0;j<reviews.size();j++)  {
      out.write("\r\n");
      out.write("\t<div id=\"review_");
      out.print(reviews.get(j).getReviewId() );
      out.write("\" class=\"well well-lg\">\r\n");
      out.write("\t<h4><em>");
      out.print(reviews.get(j).getTitle() );
      out.write("</em></h4>\r\n");
      out.write("\t<p><em>");
      out.print(reviews.get(j).getReview() );
      out.write("</em></p>\r\n");
      out.write("\t\r\n");
      out.write("\t<p><em>User : ");
      out.print( reviews.get(j).getUserName());
      out.write("</em></p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t<h4>Add Reviews</h4>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label for=\"exampleInputEmail1\">Title</label>\r\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"title\" placeholder=\"Title\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label for=\"exampleInputPassword1\">Review</label>\r\n");
      out.write("    <textarea  class=\"form-control\" id=\"review\">\r\n");
      out.write("    </textarea>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <button type=\"submit\" class=\"btn btn-success form-control\" onclick=\"ajaxAddReview();\">Submit</button>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
